Upgrade wine9.0 and add patches
flathub/org.vinegarhq.Vinegar pull request #14
Opened 2024-01-16 21:13 UTC by lunarlettuce

2024-01-16 21:42 UTC, lunarlettuce commented
bot, build org.vinegarhq.Vinegar

2024-01-17 17:43 UTC, PhoenixCausesOof commented
The build fails at the “Validate build” step.

```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions repo repo
 in dir /srv/buildbot/worker/build-x86_64-4/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions repo repo'
 using PTY: False
{
    "errors": [
        "desktop-file-is-hidden"
    ],
    "warnings": [
        "appstream-summary-too-long",
        "appstream-screenshot-missing-caption"
    ]
}
program finished with exit code 1
elapsedTime=56.919080
```

So, apparently the linter detects that the desktop file is hidden? Not sure how that happened — the patches are completely unrelated to this.

Oh well, I've never worked with Flatpak before, so I don't have a say.

2024-01-18 21:15 UTC, lunarlettuce commented
bot, build org.vinegarhq.Vinegar

2024-01-23 12:50 UTC, apprehensions requested changes

2024-01-23 12:50 UTC, apprehensions commented on org.vinegarhq.Vinegar.metainfo.xml
> +					<li>Makefile now removes svg on uninstallation</li>
```suggestion
```

2024-01-23 12:50 UTC, apprehensions commented on org.vinegarhq.Vinegar.metainfo.xml
> +					<li>Unhid the .desktop for compatibility with flathub rules</li>
```suggestion
```

2024-01-27 15:33 UTC, nyabinary commented
NixOS depends on this PR for their package  :3

2024-02-06 07:48 UTC, merged